import React, { createContext, useContext, useState, useEffect } from 'react';

const translations = {
  en: {
    // навбар
    yourWork: 'Your work',
    assignedToMe: 'Assigned to me',
    create: 'Create',
    search: 'Search',
    notifications: 'Notifications',
    help: 'Help',
    settings: 'Settings',
    logOut: 'Log out',
    language: 'Language',
    workedOn: 'Worked on',
    viewed: 'Viewed',
    starred: 'Starred',
    // доска
    board: 'Board',
    backlog: 'Backlog',
    inProgress: 'In Progress',
    done: 'Done',
    projectSettings: 'Project settings',
    summary: 'Summary',
    reports: 'Reports',
    issues: 'Issues',
    attachments: 'Attachments',
    filters: 'Filters',
    clearAll: 'Clear all',
    onlyMyIssues: 'Only My Issues',
    recentlyUpdated: 'Recently Updated',
    groupByStatus: 'Group by: Status',
    more: 'More',
    searchBoard: 'Search board',
    of: 'of',
    // сайдбар
    projects: 'Projects',
    recent: 'RECENT',
    noRecentProjects: 'No recent projects',
    viewAllProjects: 'View all projects',
    createProject: 'Create project',
    categorySoftware: 'Software',
    categoryMarketing: 'Marketing',
    categoryDesign: 'Design',
    categoryOther: 'Other',
    // настройки проекта
    projectDetails: 'Project Details',
    requiredFieldsNote: 'Required fields are marked with an asterisk',
    name: 'Name',
    projectIcon: 'Project Icon',
    chooseIconDesc: 'Choose an icon',
    uploadImageDesc: 'Upload an image and pick a background colour',
    chooseImage: 'Choose image',
    background: 'Background',
    identifier: 'Identifier',
    identifierDisabledTip: 'Cannot be changed after creation. Used in URLs.',
    description: 'Description',
    descriptionTip: 'Describe the project in as much detail as you\'d like.',
    homepage: 'Homepage',
    homepagePlaceholder: 'Link to project homepage (optional)',
    access: 'Access',
    inheritMembers: 'Inherit members',
    saveChanges: 'Save changes',
    saving: 'Saving...',
    deleteProject: 'Delete project',
    deleting: 'Deleting...',
    deleteProjectTitle: 'Delete project',
    deleteProjectMessage: 'Are you sure you want to delete {projectName}? This action will permanently delete the project, all its issues, and associated data. This cannot be undone.',
    cancel: 'Cancel',
    changesSaved: 'Changes have been saved successfully.',
    projectDeleted: 'Project deleted.',
    projectDeleteFailed: 'Failed to delete project.',
    // Your Work / All Projects
    recentProjects: 'Recent projects',
    myOpenIssues: 'My open issues',
    doneIssues: 'Done issues',
    noDescription: 'No description',
    loadingTasks: 'Loading tasks...',
    recentlyUpdatedByYou: 'Recently updated by you',
    openTasksAssignedToMe: 'Open tasks assigned to me',
    viewedComingSoon: 'Viewed items (coming soon)',
    starredComingSoon: 'Starred (coming soon)',
    noTasksFound: 'No tasks found',
    unknown: 'Unknown',
    unknownProject: 'Unknown project',
    allProjects: 'All projects',
    projectsHeader: 'Projects',
    createProjectHeader: '+ Create project',
    identifierLabel: 'Identifier',
    accessLabel: 'Access',
    membersLabel: 'Members',
    publicAccess: 'Public',
    privateAccess: 'Private',
    inherited: 'Inherited',
    notInherited: 'Not inherited',
    allTasks: 'All tasks',
    completedText: '{closed} of {total} completed',
    // Создание проекта
    backToYourWork: '← Back to your work',
    createProjectTitle: 'Create project',
    createProjectDesc: 'Explore what’s possible when you collaborate with your team. Edit project details anytime in project settings.',
    namePlaceholder: 'e.g. Landing Page',
    optionalDescription: 'Optional description',
    showMore: 'Show more',
    showLess: 'Show less',
    key: 'Key',
    creating: 'Creating...',
    createProjectBtn: 'Create Project',
    projectCreated: 'Project created!',
    // Аутентификация
    apiVerification: 'API‑key verification',
    signInTitle: 'Sign in with API‑key',
    apiKeyLabel: 'API‑Key',
    apiKeyPlaceholder: 'Paste your Redmine API key',
    verifying: 'Verifying…',
    continueBtn: 'Continue',
    apiKeyHint: 'Your API‑key is available in your Redmine account settings.',
    checkingSaved: 'Checking saved API key…',
    enterApiKey: 'Please enter your API key',
    loginSuccess: 'Login successful',
    invalidApiKey: 'Invalid API key. Check your Redmine account settings.',
    // Создание задачи (IssueCreate)
    newIssue: 'Create Issue',
    summary: 'Summary',
    summaryPlaceholder: 'What needs to be done?',
    descriptionPlaceholder: 'Add details, steps to reproduce, or acceptance criteria...',
    attachmentsDrop: 'Drop files here or click to browse',
    parentIssue: 'Parent Issue',
    parentIssuePlaceholder: 'Search by issue key or ID...',
    assignee: 'Assignee',
    unassigned: 'Unassigned',
    priority: 'Priority',
    startDate: 'Start date',
    dueDate: 'Due date',
    originalEstimate: 'Original estimate',
    donePercent: 'Done (%)',
    cancelBtn: 'Cancel',
    createBtn: 'Create',
    creatingBtn: 'Creating...',
    projectSelect: 'Project *',
    selectProject: 'Select a project',
    loadingConfig: 'Loading configuration…',
    retry: 'Retry',
    issueCreated: 'Issue created successfully!',
    // Поиск задач (IssueSearch)
    searchPlaceholder: 'Search issues by summary...',
    recentIssues: 'Recent Issues',
    matchingIssues: 'Matching Issues',
    searchNoResults: 'We couldn\'t find anything matching your search',
    searchNoResultsTip: 'Try again with a different term.',
    // Детали задачи (LeftPanel, RightPanel)
    details: 'Details',
    editFields: 'Edit fields',
    status: 'Status',
    attach: 'Attach',
    assigneeLabel: 'Assignee',
    reporter: 'Reporter',
    priorityLabel: 'Priority',
    startDateLabel: 'Start date',
    dueDateLabel: 'Due date',
    timeTracking: 'Time tracking',
    noEstimate: 'No estimate',
    none: 'None',
    hideEmptyFields: 'Hide empty fields',
    showEmptyFields: 'Show empty fields',
    save: 'Save',
    cancelEdit: 'Cancel',
    created: 'Created',
    updated: 'Updated',
    addChildIssue: 'Add a child issue',
    addRelation: 'Add relation',
    relations: 'Relations',
    descriptionLabel: 'Description',
    noDescription: 'No description',
    activity: 'Activity',
    showLabel: 'Show:',
    all: 'All',
    comments: 'Comments',
    history: 'History',
    workLog: 'Work log',
    newestFirst: 'Newest first',
    oldestFirst: 'Oldest first',
    unsavedChanges: 'You have unsaved changes. Are you sure you want to close?',
    // общие
    noTasks: 'No tasks assigned',
    loading: 'Loading...',
    priorityLow: 'Low',
    priorityMedium: 'Medium',
    priorityHigh: 'High',
    priorityCritical: 'Critical',
    visibility: 'Visibility',
    statusDistribution: 'Status distribution',
    progress: 'Progress',
    openTasks: 'Open tasks',
    closedTasks: 'Closed tasks',
    byPriority: 'By priority',
    byTracker: 'By tracker',


  },
  ru: {
    yourWork: 'Ваша работа',
    assignedToMe: 'Назначено мне',
    create: 'Создать',
    search: 'Поиск',
    notifications: 'Уведомления',
    help: 'Помощь',
    settings: 'Настройки',
    logOut: 'Выйти',
    language: 'Язык',
    workedOn: 'Недавние',
    viewed: 'Просмотренные',
    starred: 'Избранные',
    board: 'Доска',
    backlog: 'Бэклог',
    inProgress: 'В работе',
    done: 'Готово',
    projectSettings: 'Настройки проекта',
    summary: 'Сводка',
    reports: 'Отчёты',
    issues: 'Задачи',
    attachments: 'Вложения',
    filters: 'Фильтры',
    clearAll: 'Очистить всё',
    onlyMyIssues: 'Только мои задачи',
    recentlyUpdated: 'Недавно обновлённые',
    groupByStatus: 'Группировать: Статус',
    more: 'Ещё',
    searchBoard: 'Поиск по доске',
    of: 'из',
    projects: 'Проекты',
    recent: 'НЕДАВНИЕ',
    noRecentProjects: 'Нет недавних проектов',
    viewAllProjects: 'Все проекты',
    createProject: 'Создать проект',
    categorySoftware: 'ПО',
    categoryMarketing: 'Маркетинг',
    categoryDesign: 'Дизайн',
    categoryOther: 'Другое',
    projectDetails: 'Детали проекта',
    requiredFieldsNote: 'Обязательные поля отмечены звёздочкой',
    name: 'Название',
    projectIcon: 'Иконка проекта',
    chooseIconDesc: 'Выберите иконку',
    uploadImageDesc: 'Загрузите изображение и выберите цвет фона',
    chooseImage: 'Выбрать изображение',
    background: 'Фон',
    identifier: 'Идентификатор',
    identifierDisabledTip: 'Нельзя изменить после создания. Используется в URL.',
    description: 'Описание',
    descriptionTip: 'Опишите проект настолько подробно, насколько хотите.',
    homepage: 'Домашняя страница',
    homepagePlaceholder: 'Ссылка на домашнюю страницу проекта (необязательно)',
    access: 'Доступ',
    inheritMembers: 'Наследовать участников',
    saveChanges: 'Сохранить изменения',
    saving: 'Сохранение...',
    deleteProject: 'Удалить проект',
    deleting: 'Удаление...',
    deleteProjectTitle: 'Удалить проект',
    deleteProjectMessage: 'Вы уверены, что хотите удалить {projectName}? Это действие навсегда удалит проект, все его задачи и связанные данные. Это действие нельзя отменить.',
    cancel: 'Отмена',
    changesSaved: 'Изменения успешно сохранены.',
    projectDeleted: 'Проект удалён.',
    projectDeleteFailed: 'Не удалось удалить проект.',
    recentProjects: 'Недавние проекты',
    myOpenIssues: 'Мои открытые задачи',
    doneIssues: 'Завершённые задачи',
    noDescription: 'Нет описания',
    loadingTasks: 'Загрузка задач...',
    recentlyUpdatedByYou: 'Недавно обновлённые вами',
    openTasksAssignedToMe: 'Открытые задачи, назначенные мне',
    viewedComingSoon: 'Просмотренные (скоро)',
    starredComingSoon: 'Избранные (скоро)',
    noTasksFound: 'Задачи не найдены',
    unknown: 'Неизвестно',
    unknownProject: 'Неизвестный проект',
    allProjects: 'Все проекты',
    projectsHeader: 'Проекты',
    createProjectHeader: '+ Создать проект',
    identifierLabel: 'Идентификатор',
    accessLabel: 'Доступ',
    membersLabel: 'Участники',
    publicAccess: 'Публичный',
    privateAccess: 'Приватный',
    inherited: 'Наследуемые',
    notInherited: 'Не наследуемые',
    allTasks: 'Все задачи',
    completedText: '{closed} из {total} завершено',
    backToYourWork: '← Назад к работе',
    createProjectTitle: 'Создать проект',
    createProjectDesc: 'Исследуйте возможности совместной работы с командой. Детали можно изменить в настройках проекта.',
    namePlaceholder: 'например, Landing Page',
    optionalDescription: 'Описание (необязательно)',
    showMore: 'Показать больше',
    showLess: 'Скрыть',
    key: 'Ключ',
    creating: 'Создание...',
    createProjectBtn: 'Создать проект',
    projectCreated: 'Проект создан!',
    apiVerification: 'Проверка API‑ключа',
    signInTitle: 'Вход по API‑ключу',
    apiKeyLabel: 'API‑Ключ',
    apiKeyPlaceholder: 'Вставьте ваш Redmine API‑ключ',
    verifying: 'Проверка…',
    continueBtn: 'Продолжить',
    apiKeyHint: 'Ваш API‑ключ доступен в настройках аккаунта Redmine.',
    checkingSaved: 'Проверка сохранённого ключа…',
    enterApiKey: 'Введите API‑ключ',
    loginSuccess: 'Вход выполнен успешно',
    invalidApiKey: 'Неверный API‑ключ. Проверьте настройки аккаунта Redmine.',
    newIssue: 'Новая задача',
    summary: 'Тема',
    summaryPlaceholder: 'Что нужно сделать?',
    descriptionPlaceholder: 'Добавьте описание, шаги воспроизведения или критерии приёмки...',
    attachmentsDrop: 'Перетащите файлы или нажмите для выбора',
    parentIssue: 'Родительская задача',
    parentIssuePlaceholder: 'Поиск по ключу или ID задачи...',
    assignee: 'Исполнитель',
    unassigned: 'Не назначен',
    priority: 'Приоритет',
    startDate: 'Дата начала',
    dueDate: 'Срок',
    originalEstimate: 'Оценка (часы)',
    donePercent: 'Готовность (%)',
    cancelBtn: 'Отмена',
    createBtn: 'Создать',
    creatingBtn: 'Создание...',
    projectSelect: 'Проект *',
    selectProject: 'Выберите проект',
    loadingConfig: 'Загрузка конфигурации…',
    retry: 'Повторить',
    issueCreated: 'Задача успешно создана!',
    searchPlaceholder: 'Поиск задач по теме...',
    recentIssues: 'Недавние задачи',
    matchingIssues: 'Найденные задачи',
    searchNoResults: 'Ничего не найдено по вашему запросу',
    searchNoResultsTip: 'Попробуйте изменить условия поиска.',
    details: 'Детали',
    editFields: 'Редактировать поля',
    status: 'Статус',
    attach: 'Прикрепить',
    assigneeLabel: 'Исполнитель',
    reporter: 'Автор',
    priorityLabel: 'Приоритет',
    startDateLabel: 'Дата начала',
    dueDateLabel: 'Срок',
    timeTracking: 'Учёт времени',
    noEstimate: 'Без оценки',
    none: 'Нет',
    hideEmptyFields: 'Скрыть пустые поля',
    showEmptyFields: 'Показать пустые поля',
    save: 'Сохранить',
    cancelEdit: 'Отмена',
    created: 'Создано',
    updated: 'Обновлено',
    addChildIssue: 'Добавить подзадачу',
    addRelation: 'Добавить связь',
    relations: 'Связи',
    descriptionLabel: 'Описание',
    noDescription: 'Нет описания',
    activity: 'Активность',
    showLabel: 'Показать:',
    all: 'Все',
    comments: 'Комментарии',
    history: 'История',
    workLog: 'Журнал работ',
    newestFirst: 'Сначала новые',
    oldestFirst: 'Сначала старые',
    unsavedChanges: 'Есть несохранённые изменения. Уверены, что хотите закрыть?',
    noTasks: 'Нет назначенных задач',
    loading: 'Загрузка...',
    priorityLow: 'Низкий',
    priorityMedium: 'Средний',
    priorityHigh: 'Высокий',
    priorityCritical: 'Критический',
    visibility: 'Видимость',
    statusDistribution: 'Распределение по статусам',
    progress: 'Прогресс',
    openTasks: 'Открытых задач',
    closedTasks: 'Закрытых задач',
    byPriority: 'По приоритету',
    byTracker: 'По типу задачи',
  },
};

const LanguageContext = createContext();

export const LanguageProvider = ({ children }) => {
  const [locale, setLocale] = useState(localStorage.getItem('appLanguage') || 'en');

  const switchLanguage = (lang) => {
    localStorage.setItem('appLanguage', lang);
    setLocale(lang);
  };

  // При смене языка добавляем/убираем класс для кастомного шрифта
  useEffect(() => {
    if (locale === 'ru') {
      document.body.classList.add('font-ru');
    } else {
      document.body.classList.remove('font-ru');
    }
  }, [locale]);

  const t = (key, vars) => {
    let text = translations[locale]?.[key] || key;
    if (vars) {
      Object.keys(vars).forEach(v => {
        text = text.replace(`{${v}}`, vars[v]);
      });
    }
    return text;
  };

  return (
    <LanguageContext.Provider value={{ locale, switchLanguage, t }}>
      {children}
    </LanguageContext.Provider>
  );
};

export const useLanguage = () => useContext(LanguageContext);